### ISSUE TITLE
[HW/SW]Watchdog por hardware

### ISSUE THREAD

**Issue by darkjavi** [makespacemadrid/Jarvis#27]
En relacion a #7.

La estabilidad del firmware ha mejorado muchísimo con las ultimas versiones de la integración con arduino, especialmente la ultima versión de desarrollo (2.1-rc2). Aun así se quedan pegados alguna vez y seria muy útil tener un reset por hardware;
Algún tipo de circuito de condensadores/resistencias que si no recibe una pulsación periódica de una patilla del esp le de una pulsación al reset del micro.
¿Ideas?

**Comment by darkjavi** [comment]
Mirar la posibilidad de instalar un pequeño microcontrolador para hacer de perro guardian:
http://www.electronicaembajadores.com/Productos/Detalle/-1/SMCIATTINY85/microcontrolador-attiny85-20pu

**Comment by trastejantEdu** [comment]
Igual complicamos -y encarecemos- los modulos, pero según lo veo simplemente necesitamos enviar a un alive a este chip cada n X ms, el alive reinicia el contador del tiny. Si no recibimos un alive el tiny levanta el reset del ESP. 

Seguro que esto tiene alguna pega que ahora mismo se me escapa... Pero se puede intentar. ¿Tenemos quemadores en el espacio para este chip?

**Comment by darkjavi** [comment]
Hay ya una primera implementacion super sencilla, el esp conectado a una patilla de un nano, cambiando el estado de una patilla cada 5 segundos. 
Si la patilla no cambia de estado en 20 segundos el Nano le pega un reset al esp.
Ese mismo nano podría ser el que lee sensores por i2c.

Si quieres echarle un ojo esta en la carpeta watchdog firmware del repo :)

**Comment by trastejantEdu** [comment]
Tengo que mirarme todo el código... ya tengo un ordenador decente XD
