### ISSUE TITLE
El compilador no encuentra <vector>

### ISSUE THREAD

**Issue by gmag11** [makespacemadrid/Jarvis#28]
Al intentar compilar sale el error:

`communication.h:In file included from`
`jarvisNode.h:from`
`JarvisFirmware.ino:from`
`jarvisParser.h:7:18: fatal error: vector: No such file or directory`
`:#include <vector>`
`:compilation terminated`
`Error compiling project sources`

He añadido la librería StandardCplusplus de tu repositorio con el entorno de Arduino.

Estoy usando el entorno Arduino ESP descargado directamente desde GitHub y un ESP12 de 4 MB

**Comment by darkjavi** [comment]
Como estas compilando?
Me suena a que se esta intentando compilar para arduino en vez de para el ESP, la clase vector va de serie en complemento que se le mete al arduino para hacer código para el ESP y la librería la tenia para dar la compatibilidad con arduinos.
