### ISSUE TITLE
Arduino Nano casi sin memoria

### ISSUE THREAD

**Issue by darkjavi** [makespacemadrid/Jarvis#6]
El firmware esta ya tochete y apenas entra en el arduino Nano (99% en este momento).

He creado un par de etiquetas para ir poniendo por el codigo y arañar algunos bites aquí y allá.
# define VERBOSE_DEBUG

```
Serial.println("Literales de texto que comen mazo de memoria")
```
# endif
# define BIG_FLASH

  void funcionQueIgualNoHaceFaltaEnElNano()
      {
          blabla();
      }
# endif

A parte de eso se puede ganar bastante memoria cambiando las cadenas del protocolo por algo menos descriptivo y mas corto p.e. wifistatus - > ws, ahí si que creo que hay un montón de bytes que se pueden sacar.

**Comment by darkjavi** [comment]
Otra idea para resolverlo pordria ser desactivar la eeprom(4K) en el Nano, dejando todos los settings en el esp y proveyendo de mecanismos para recuperar los settings.

**Comment by trastejantEdu** [comment]
Tambien podemos almacenar algunos parametros de configuracion en la SD.
